work in progress on api-tokens
divviup/divviup-api pull request #233
Opened 2023-06-26 17:31 UTC by jbr

sharing draft in case anyone wants to skim because i'm pausing work on it to get #216-related stuff done

2023-06-27 18:16 UTC, divergentdave requested changes

2023-06-27 20:32 UTC, jbr commented on migration/src/lib.rs
> +            Box::new(m20230623_175314_create_api_tokens::Migration),
In addition to fixing this case I want to do a survey of migration approaches in other frameworks (particularly elixir's ecto). I think sea orm is wrong here; migrations needn't be applied in ID/timestamp order. But we should use sea orm's migration tooling how they want us to until something better comes along / I carve out some time to write something better

2023-06-30 20:00 UTC, jbr commented on migration/src/lib.rs
> +            Box::new(m20230623_175314_create_api_tokens::Migration),
resolved in rebase

2023-06-30 20:02 UTC, divergentdave approved these changes

2023-06-30 20:20 UTC, merged